k

diff --git a/.github/workflows/Build_Kernel.yml b/.github/workflows/Build_Kernel.yml
--- a/.github/workflows/Build_Kernel.yml
+++ b/.github/workflows/Build_Kernel.yml
@@ -26,6 +26,14 @@ on:
           - 'psyche'
           - 'pipa'
           - 'all'
+      compiled_system:
+        description: 'Applicable systems (适用系统)'
+        required: true
+        type: choice
+        default: 'MIUI'
+        options:
+          - 'MIUI'
+          - 'AOSP'
       kernelsu_enable:
         description: 'Is Ksu support enabled? (是否启用 kernelsu 支持?)'
         required: true
@@ -91,7 +99,7 @@ jobs:
     steps:
       - name: 📢 Build Information (构建信息)
         run: |
-          echo "设备: ${DEVICE}"
+          echo "设备: ${DEVICE} | 系统: ${{ github.event.inputs.compiled_system }}"
           echo "KernelSU支持: ${{ github.event.inputs.kernelsu_enable }}"
           echo "构建类型: ${{ github.event.inputs.build_type }}"
 
@@ -157,6 +165,7 @@ jobs:
       - name: 🔨 Build the kernel (构建内核)
         run: |
           cd $KERNEL_SOURCE
+          SYSTEM="${{ github.event.inputs.compiled_system }}"
           KSU_enable="${{ github.event.inputs.kernelsu_enable }}"
           VERSION="${{ github.event.inputs.kernel_version }}"
 
@@ -188,7 +197,150 @@ jobs:
             sed -i "s/echo \"\$res\"/echo \"${custom_part}\"/g" "$KERNEL_SOURCE/scripts/setlocalversion"
           fi
 
-          bash build.sh "$DEVICE" "$KSU_enable"
+          TOOLCHAIN_PATH=$HOME/proton-clang/proton-clang-20210522/bin
+          GIT_COMMIT_ID=$(git rev-parse --short=8 HEAD)
+
+          echo "TOOLCHAIN_PATH: [$TOOLCHAIN_PATH]"
+          export PATH="$TOOLCHAIN_PATH:$PATH"
+
+          # Enable ccache for speed up compiling 
+          export CCACHE_DIR="$HOME/.cache/ccache_mikernel" 
+          export CC="ccache gcc"
+          export CXX="ccache g++"
+          export PATH="/usr/lib/ccache:$PATH"
+          echo "CCACHE_DIR: [$CCACHE_DIR]"
+
+          MAKE_ARGS="ARCH=arm64 SUBARCH=arm64 O=out CC=clang CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- CROSS_COMPILE_COMPAT=arm-linux-gnueabi- CLANG_TRIPLE=aarch64-linux-gnu-"
+
+          # Check clang is existing.
+          echo "[clang --version]:"
+          clang --version
+
+          KSU_ZIP_STR=NoKernelSU
+          if [ "$KSU_enable" == "ksu" ]; then
+              KSU_ENABLE=1
+              KSU_ZIP_STR=SukiSU-SUSFS
+          else
+              KSU_ENABLE=0
+          fi
+
+          echo "TARGET_DEVICE: $DEVICE"
+
+          if [ $KSU_ENABLE -eq 1 ]; then
+              echo "KSU is enabled"
+              curl -LSs "https://raw.githubusercontent.com/ShirkNeko/SukiSU-Ultra/main/kernel/setup.sh" | bash -s bdf675b448b169ff6721e1af30b23b904d9757ae
+          else
+              echo "KSU is disabled"
+          fi
+
+          echo "Cleaning..."
+
+          rm -rf out/
+          rm -rf anykernel/
+
+          echo "Clone AnyKernel3 for packing kernel (repo: https://github.com/liyafe1997/AnyKernel3)"
+          git clone https://github.com/liyafe1997/AnyKernel3 -b kona --single-branch --depth=1 anykernel
+
+          echo "Building Image......"
+          make $MAKE_ARGS ${DEVICE}_defconfig
+
+          if [ $KSU_ENABLE -eq 1 ]; then
+              scripts/config --file out/.config \
+              -e KSU \
+              -e KSU_MANUAL_HOOK \
+              -e KSU_SUSFS_HAS_MAGIC_MOUNT \
+              -d KSU_SUSFS_SUS_PATH \
+              -e KSU_SUSFS_SUS_MOUNT \
+              -e KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT \
+              -e KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT \
+              -e KSU_SUSFS_SUS_KSTAT \
+              -d KSU_SUSFS_SUS_OVERLAYFS \
+              -e KSU_SUSFS_TRY_UMOUNT \
+              -e KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT \
+              -e KSU_SUSFS_SPOOF_UNAME \
+              -e KSU_SUSFS_ENABLE_LOG \
+              -e KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS \
+              -e KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG \
+              -d KSU_SUSFS_OPEN_REDIRECT \
+              -d KSU_SUSFS_SUS_SU \
+              -e KPM
+          else
+              scripts/config --file out/.config -d KSU
+          fi
+
+          if [ "$SYSTEM" == "MIUI" ]; then
+              scripts/config --file out/.config \
+                  --set-str STATIC_USERMODEHELPER_PATH /system/bin/micd \
+                  -e PERF_CRITICAL_RT_TASK	\
+                  -e SF_BINDER		\
+                  -e OVERLAY_FS		\
+                  -d DEBUG_FS \
+                  -e MIGT \
+                  -e MIGT_ENERGY_MODEL \
+                  -e MIHW \
+                  -e PACKAGE_RUNTIME_INFO \
+                  -e BINDER_OPT \
+                  -e KPERFEVENTS \
+                  -e MILLET \
+                  -e PERF_HUMANTASK \
+                  -d LTO_CLANG \
+                  -d LOCALVERSION_AUTO \
+                  -e SF_BINDER \
+                  -e XIAOMI_MIUI \
+                  -d MI_MEMORY_SYSFS \
+                  -e TASK_DELAY_ACCT \
+                  -e MIUI_ZRAM_MEMORY_TRACKING \
+                  -d CONFIG_MODULE_SIG_SHA512 \
+                  -d CONFIG_MODULE_SIG_HASH \
+                  -e MI_FRAGMENTION \
+                  -e PERF_HELPER \
+                  -e BOOTUP_RECLAIM \
+                  -e MI_RECLAIM \
+                  -e RTMM \
+          fi
+
+          make $MAKE_ARGS -j$(nproc)
+
+          if [ -f "out/arch/arm64/boot/Image" ]; then
+              echo "The file [out/arch/arm64/boot/Image] exists. MIUI Build successfully."
+          else
+              echo "The file [out/arch/arm64/boot/Image] does not exist. Seems MIUI build failed."
+              exit 1
+          fi
+
+          echo "Generating [out/arch/arm64/boot/dtb]......"
+          find out/arch/arm64/boot/dts -name '*.dtb' -exec cat {} + >out/arch/arm64/boot/dtb
+
+          # Restore modified dts
+          rm -rf ${dts_source}
+          mv .dts.bak ${dts_source}
+
+          rm -rf anykernel/kernels/
+          mkdir -p anykernel/kernels/
+
+          # Patch for SukiSU KPM support. 
+          if [ $KSU_ENABLE -eq 1 ]; then
+              cd out/arch/arm64/boot/
+              wget https://github.com/SukiSU-Ultra/SukiSU_KernelPatch_patch/releases/download/0.12.0/patch_linux
+              chmod +x patch_linux
+              ./patch_linux
+              rm Image
+              mv oImage Image
+              cd -
+          fi
+
+          cp out/arch/arm64/boot/Image anykernel/kernels/
+          cp out/arch/arm64/boot/dtb anykernel/kernels/
+
+          cd anykernel 
+
+          ZIP_FILENAME=Kernel_${SYSTEM}_${DEVICE}_${KSU_ZIP_STR}_$(date +'%Y%m%d_%H%M%S')_anykernel3_${GIT_COMMIT_ID}.zip
+
+          zip -r9 $ZIP_FILENAME ./* -x .git .gitignore out/ ./*.zip
+
+          mv $ZIP_FILENAME ../
+
+          echo "Done. The flashable zip is: [./$ZIP_FILENAME]"
 
           mkdir -p "${WORKDIR}/out" || {
               echo "无法创建目录：${WORKDIR}/out" >&2
@@ -204,20 +356,12 @@ jobs:
           }
 
           echo "操作成功完成！"
-          GIT_COMMIT_SHORT=$(git rev-parse --short=13 HEAD)
-          echo "GIT_COMMIT_ID=$GIT_COMMIT_ID" >> $GITHUB_ENV
 
-      - name: 📤 Upload AOSP compilation results (上传AOSP编译结果)
+      - name: 📤 Upload compilation results (上传编译结果)
         uses: actions/upload-artifact@v4
         with:
-          name: Kernel-AOSP-${{ matrix.device }}
-          path: ${{ github.workspace }}/out/Kernel_AOSP_*.zip
-
-      - name: 📤 Upload MIUI compilation results (上传MIUI编译结果)
-        uses: actions/upload-artifact@v4
-        with:
-          name: Kernel-MIUI-${{ matrix.device }}
-          path: ${{ github.workspace }}/out/Kernel_MIUI_*.zip
+          name: Kernel-${{ matrix.device }}
+          path: ${{ github.workspace }}/out/Kernel_*
 
   release:
     needs: build
@@ -240,7 +384,7 @@ jobs:
         cd ${{ github.workspace }}/out
         device_list=()
         for dir in */; do
-          device_name=$(echo "$dir" | sed 's/Kernel-MIUI-//' | sed 's/Kernel-AOSP-//' | sed 's/\/$//')
+          device_name=$(echo "$dir" | sed 's/Kernel-//' | sed 's/\/$//')
           echo "Found device: $device_name"
           device_list+=("$device_name")
           cd "$dir"
@@ -262,17 +406,17 @@ jobs:
       uses: softprops/action-gh-release@v1
       with:
         files: ${{ github.workspace }}/release/*.zip
-        name: Kernel_(${{ env.TARGET_DEVICES }})_${{ github.event.inputs.kernelsu_variant }}_${{ env.RELEASE_DATE }}_${{ env.GIT_COMMIT_ID }}_${{ github.event.inputs.build_type }}
-        tag_name: Kernel_(${{ env.TARGET_DEVICES }})_${{ github.event.inputs.kernelsu_variant }}_${{ env.RELEASE_DATE }}_${{ env.GIT_COMMIT_ID }}
+        name: Kernel_(${{ env.TARGET_DEVICES }})_${{ github.event.inputs.kernelsu_variant }}_${{ github.event.inputs.compiled_system }}_${{ env.RELEASE_DATE }}_${{ env.GIT_COMMIT_ID }}_${{ github.event.inputs.build_type }}
+        tag_name: Kernel_(${{ env.TARGET_DEVICES }})_${{ github.event.inputs.kernelsu_variant }}_${{ github.event.inputs.compiled_system }}_${{ env.RELEASE_DATE }}_${{ env.GIT_COMMIT_ID }}
         body: |
           ## 📱kernel build information | 内核构建信息
           
           ### 🇨🇳 中文 | Chinese
           - **目标机型:** ${{ env.TARGET_DEVICES }}
+          - **适用系统:** ${{ github.event.inputs.compiled_system }}
           - **KernelSU支持:** ${{ github.event.inputs.kernelsu_enable }}
           - **构建类型:** ${{ github.event.inputs.build_type }}
           - **构建日期:** ${{ env.RELEASE_DATE }}
-          - **提交ID:** ${{ env.GIT_COMMIT_ID }}
       
           ### 📋 安装说明 | Installation Guide
           1. 下载对应机型的刷机包
